name: $(buildversion)

trigger:
  branches:
    include:
      - main
      - features/*
  paths:
    include:
      - azuredevops/powerbiactions-xplat
      - pipelines/powerbiactions-xplat.yml

pr:
  branches:
    include:
      - main
      - features/*
  paths:
    include:
      - azuredevops/powerbiactions-xplat
      - pipelines/powerbiactions-xplat.yml

variables:
  - group: "Marketplace"
  - group: "Version Number"
  - template: variables/powerbiaction-xplat.variables.yml
  
stages:
  - stage: build
    displayName: Build
    jobs:
      - job:
        pool:
          vmImage: "windows-latest"
          demands: azureps
        continueOnError: false
        steps:
          - template: steps/build-node.yml
            parameters:
              extensiondirectory: "azuredevops/powerbiactions-xplat/powerbiactionsxplat"
  - stage: Beta
    displayName: Test
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: DeployTest
        displayName: Deploy Extension to Test
        pool:
          vmImage: "windows-latest"
          demands: azureps
        environment: "Extensions test"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: steps/test.yml
  - stage: Publish
    displayName: Publish
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: DeployPRD
        displayName: Deploy Extension to Public Publisher
        pool:
          vmImage: "windows-latest"
          demands: azureps
        environment: "Public publisher"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: steps/publish.yml